In [12]:
import pandas as pd

In [13]:
# 22 covid isolation
# 24 dependents
# 40 feeling isolated
# 41 trust
# 81 extravert
# 82 reserved
# 109 distress
df = pd.read_csv('./data/COVIDiSTRESS.csv', usecols=[22, 24, 40, 41, 81, 82, 109], skiprows=[1,2])

In [14]:
df

,Dem_islolation,Dem_isolation_kids,Scale_PSS10_UCLA_13,OECD_people_1,BFF_15_5,BFF_15_6,Expl_Distress_18
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Life carries on with minor changes,1.0,Very often,5.0,Agree,Slightly agree,Strongly agree
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Life carries on with minor changes,NaN,Never,7.0,Slightly disagree,Agree,Strongly disagree
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
139221,Isolated,6.0,Fairly often,3.0,Disagree,Agree,Agree
139222,Life carries on with minor changes,0.0,Almost never,7.0,Agree,Disagree,Disagree
139223,NaN,NaN,NaN,NaN,NaN,NaN,NaN
139224,NaN,NaN,NaN,NaN,NaN,NaN,NaN
139225,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df.shape

(139226, 7)

In [16]:
df = df.dropna()

In [17]:
df.shape

(66745, 7)

In [18]:
df

,Dem_islolation,Dem_isolation_kids,Scale_PSS10_UCLA_13,OECD_people_1,BFF_15_5,BFF_15_6,Expl_Distress_18
1,Life carries on with minor changes,1.0,Very often,5.0,Agree,Slightly agree,Strongly agree
5,Isolated,0.0,Fairly often,7.0,Slightly agree,Slightly agree,Slightly agree
6,Isolated,0.0,Sometimes,0.0,Strongly disagree,Strongly disagree,Strongly disagree
8,Life carries on with minor changes,0.0,Fairly often,5.0,Agree,Slightly agree,Agree
11,Life carries on with minor changes,0.0,Fairly often,7.0,Agree,Agree,Slightly agree
...,...,...,...,...,...,...,...
139216,Isolated,0.0,Fairly often,1.0,Slightly disagree,Agree,Strongly agree
139219,Life carries on with minor changes,1.0,Sometimes,5.0,Slightly disagree,Slightly disagree,Slightly disagree
139220,Isolated,0.0,Fairly often,5.0,Agree,Disagree,Agree
139221,Isolated,6.0,Fairly often,3.0,Disagree,Agree,Agree
139222,Life carries on with minor changes,0.0,Almost never,7.0,Agree,Disagree,Disagree

In [19]:
df.head

<bound method NDFrame.head of                             Dem_islolation  Dem_isolation_kids  \
1       Life carries on with minor changes                 1.0
5                                 Isolated                 0.0
6                                 Isolated                 0.0
8       Life carries on with minor changes                 0.0
11      Life carries on with minor changes                 0.0
...                                    ...                 ...
139216                            Isolated                 0.0
139219  Life carries on with minor changes                 1.0
139220                            Isolated                 0.0
139221                            Isolated                 6.0
139222  Life carries on with minor changes                 0.0

       Scale_PSS10_UCLA_13  OECD_people_1           BFF_15_5  \
1               Very often            5.0              Agree
5             Fairly often            7.0     Slightly agree
6                Sometimes            0.0  Strongly disagree
8             Fairly often            5.0              Agree
11            Fairly often            7.0              Agree
...                    ...            ...                ...
139216        Fairly often            1.0  Slightly disagree
139219           Sometimes            5.0  Slightly disagree
139220        Fairly often            5.0              Agree
139221        Fairly often            3.0           Disagree
139222        Almost never            7.0              Agree

                 BFF_15_6   Expl_Distress_18
1          Slightly agree     Strongly agree
5          Slightly agree     Slightly agree
6       Strongly disagree  Strongly disagree
8          Slightly agree              Agree
11                  Agree     Slightly agree
...                   ...                ...
139216              Agree     Strongly agree
139219  Slightly disagree  Slightly disagree
139220           Disagree              Agree
139221              Agree              Agree
139222           Disagree           Disagree

[66745 rows x 7 columns]>

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 66745 entries, 1 to 139222
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Dem_islolation       66745 non-null  object
 1   Dem_isolation_kids   66745 non-null  float64
 2   Scale_PSS10_UCLA_13  66745 non-null  object
 3   OECD_people_1        66745 non-null  float64
 4   BFF_15_5             66745 non-null  object
 5   BFF_15_6             66745 non-null  object
 6   Expl_Distress_18     66745 non-null  object
dtypes: float64(2), object(5)
memory usage: 4.1+ MB

In [21]:
df.describe()

       Dem_isolation_kids  OECD_people_1
count        66745.000000   66745.000000
mean             0.457457       5.563832
std              1.335217       2.083063
min              0.000000       0.000000
25%              0.000000       4.000000
50%              0.000000       6.000000
75%              1.000000       7.000000
max            110.000000      10.000000

In [22]:
df.to_csv('./data/dataset2-output.csv', index=False)