In [21]:
import pandas as pd
import math

In [22]:
# 22 covid isolation
# 30 anxious
# 40 feeling isolated
# 41 trust
# 81 extravert
# 82 reserved
# 109 distress
# 110 staying inside
df = pd.read_csv('./data/COVIDiSTRESS.csv', usecols=[22, 30,40, 41, 81, 82, 109, 110])

/usr/local/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3169: DtypeWarning: Columns (41) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [23]:
df

,Dem_islolation,Scale_PSS10_UCLA_3,Scale_PSS10_UCLA_13,OECD_people_1,BFF_15_5,BFF_15_6,Expl_Distress_18,Expl_Distress_19
0,What best describes your current situation?,"In the last week, how often have you... - felt...","In the last week, how often have you... - felt...","On a scale from zero to ten, where zero is not...","Finally, to finish the first part of the surve...","Finally, to finish the first part of the surve...","In the current situation, how much do you agre...","In the current situation, how much do you agre..."
1,"{""ImportId"":""QID17""}","{""ImportId"":""QID29_3""}","{""ImportId"":""QID29_13""}","{""ImportId"":""QID31_1""}","{""ImportId"":""QID39_5""}","{""ImportId"":""QID39_6""}","{""ImportId"":""QID40_18""}","{""ImportId"":""QID40_19""}"
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Life carries on with minor changes,Fairly often,Very often,5,Agree,Slightly agree,Strongly agree,Strongly agree
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
139223,Isolated,Fairly often,Fairly often,3.0,Disagree,Agree,Agree,Agree
139224,Life carries on with minor changes,Almost never,Almost never,7.0,Agree,Disagree,Disagree,Disagree
139225,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
139226,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
139227,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:

df = pd.read_csv('./data/COVIDiSTRESS.csv', usecols=[22, 30,40, 41, 81, 82, 109, 110], skiprows=[1,2])

In [25]:
df

,Dem_islolation,Scale_PSS10_UCLA_3,Scale_PSS10_UCLA_13,OECD_people_1,BFF_15_5,BFF_15_6,Expl_Distress_18,Expl_Distress_19
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Life carries on with minor changes,Fairly often,Very often,5.0,Agree,Slightly agree,Strongly agree,Strongly agree
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Life carries on with minor changes,Sometimes,Never,7.0,Slightly disagree,Agree,Strongly disagree,Slightly agree
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
139221,Isolated,Fairly often,Fairly often,3.0,Disagree,Agree,Agree,Agree
139222,Life carries on with minor changes,Almost never,Almost never,7.0,Agree,Disagree,Disagree,Disagree
139223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
139224,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
139225,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
df.shape

(139226, 8)

In [27]:
df = df.dropna()

In [28]:
df.shape

(79878, 8)

In [29]:
df

,Dem_islolation,Scale_PSS10_UCLA_3,Scale_PSS10_UCLA_13,OECD_people_1,BFF_15_5,BFF_15_6,Expl_Distress_18,Expl_Distress_19
1,Life carries on with minor changes,Fairly often,Very often,5.0,Agree,Slightly agree,Strongly agree,Strongly agree
3,Life carries on with minor changes,Sometimes,Never,7.0,Slightly disagree,Agree,Strongly disagree,Slightly agree
5,Isolated,Fairly often,Fairly often,7.0,Slightly agree,Slightly agree,Slightly agree,Slightly agree
6,Isolated,Sometimes,Sometimes,0.0,Strongly disagree,Strongly disagree,Strongly disagree,Strongly disagree
8,Life carries on with minor changes,Almost never,Fairly often,5.0,Agree,Slightly agree,Agree,Agree
...,...,...,...,...,...,...,...,...
139218,Life carries on with minor changes,Almost never,Never,7.0,Agree,Agree,Slightly agree,Slightly agree
139219,Life carries on with minor changes,Sometimes,Sometimes,5.0,Slightly disagree,Slightly disagree,Slightly disagree,Slightly agree
139220,Isolated,Sometimes,Fairly often,5.0,Agree,Disagree,Agree,Slightly agree
139221,Isolated,Fairly often,Fairly often,3.0,Disagree,Agree,Agree,Agree
139222,Life carries on with minor changes,Almost never,Almost never,7.0,Agree,Disagree,Disagree,Disagree

In [30]:
df.head

<bound method NDFrame.head of                             Dem_islolation Scale_PSS10_UCLA_3  \
1       Life carries on with minor changes       Fairly often
3       Life carries on with minor changes          Sometimes
5                                 Isolated       Fairly often
6                                 Isolated          Sometimes
8       Life carries on with minor changes       Almost never
...                                    ...                ...
139218  Life carries on with minor changes       Almost never
139219  Life carries on with minor changes          Sometimes
139220                            Isolated          Sometimes
139221                            Isolated       Fairly often
139222  Life carries on with minor changes       Almost never

       Scale_PSS10_UCLA_13  OECD_people_1           BFF_15_5  \
1               Very often            5.0              Agree
3                    Never            7.0  Slightly disagree
5             Fairly often            7.0     Slightly agree
6                Sometimes            0.0  Strongly disagree
8             Fairly often            5.0              Agree
...                    ...            ...                ...
139218               Never            7.0              Agree
139219           Sometimes            5.0  Slightly disagree
139220        Fairly often            5.0              Agree
139221        Fairly often            3.0           Disagree
139222        Almost never            7.0              Agree

                 BFF_15_6   Expl_Distress_18   Expl_Distress_19
1          Slightly agree     Strongly agree     Strongly agree
3                   Agree  Strongly disagree     Slightly agree
5          Slightly agree     Slightly agree     Slightly agree
6       Strongly disagree  Strongly disagree  Strongly disagree
8          Slightly agree              Agree              Agree
...                   ...                ...                ...
139218              Agree     Slightly agree     Slightly agree
139219  Slightly disagree  Slightly disagree     Slightly agree
139220           Disagree              Agree     Slightly agree
139221              Agree              Agree              Agree
139222           Disagree           Disagree           Disagree

[79878 rows x 8 columns]>

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 79878 entries, 1 to 139222
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Dem_islolation       79878 non-null  object
 1   Scale_PSS10_UCLA_3   79878 non-null  object
 2   Scale_PSS10_UCLA_13  79878 non-null  object
 3   OECD_people_1        79878 non-null  float64
 4   BFF_15_5             79878 non-null  object
 5   BFF_15_6             79878 non-null  object
 6   Expl_Distress_18     79878 non-null  object
 7   Expl_Distress_19     79878 non-null  object
dtypes: float64(1), object(7)
memory usage: 5.5+ MB

In [32]:
df.describe()

       OECD_people_1
count   79878.000000
mean        5.573900
std         2.073983
min         0.000000
25%         4.000000
50%         6.000000
75%         7.000000
max        10.000000

In [33]:
df.to_csv('./data/dataset2-output.csv', index=False)